
/**************************************************************
 *	
 *	hit, 8 bit, 11025Hz,
 *	1 channel, 2054 bytes/channel
 *	Total Size: 1 * 2054 + 4 (header) = 2098 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vy/Downloads/VyHuynh_MILESTONE2/hit.wav
 *	Time-stamp: Tue Nov 28 15:17:09 2017
 *	
 **************************************************************/

#ifndef __HITH__
#define __HITH__

#define HITFREQ 11025
#define HITLEN 2054

extern const unsigned char hit[2054];

#endif /* __HITH__ */
