
/**************************************************************
 *	
 *	pon, 8 bit, 11025Hz,
 *	1 channel, 2588429 bytes/channel
 *	Total Size: 1 * 2588429 + 4 (header) = 2588473 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vy/Downloads/VyHuynh_MILESTONE2/pon.wav
 *	Time-stamp: Tue Nov 28 05:08:59 2017
 *	
 **************************************************************/

#ifndef __PONH__
#define __PONH__

#define PONFREQ 11025
#define PONLEN 2588429

extern const unsigned char pon[2588429];

#endif /* __PONH__ */
