
/**************************************************************
 *	
 *	TRACK1, 8 bit, 11025Hz,
 *	1 channel, 560640 bytes/channel
 *	Total Size: 1 * 560640 + 4 (header) = 560684 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vy/Downloads/VyHuynh_MILESTONE2/TRACK1.wav
 *	Time-stamp: Tue Dec 05 10:48:16 2017
 *	
 **************************************************************/

#ifndef __TRACK1H__
#define __TRACK1H__

#define TRACK1FREQ 11025
#define TRACK1LEN 560640

extern const unsigned char TRACK1[560640];

#endif /* __TRACK1H__ */
