
/**************************************************************
 *	
 *	TRACK2, 8 bit, 11025Hz,
 *	1 channel, 560640 bytes/channel
 *	Total Size: 1 * 560640 + 4 (header) = 560684 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vy/Desktop/VyHuynh_MILESTONE3/MINE INC SOUNDTRACK/TRACK2.wav
 *	Time-stamp: Tue Dec 05 10:57:10 2017
 *	
 **************************************************************/

#ifndef __TRACK2H__
#define __TRACK2H__

#define TRACK2FREQ 11025
#define TRACK2LEN 560640

extern const unsigned char TRACK2[560640];

#endif /* __TRACK2H__ */
